config/routes.rb
Rails.application.routes.draw do
  get 'requests/index'
  get 'requests/show'
  get 'requests/new'
  get 'requests/requestsreceived'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/edit'
  get 'users/delete'
  get 'listings/index'
  get 'listings/show'
  get 'listings/new'
  get 'listings/edit'
  get 'listings/myproperties'


  # when you visit the homepage
  get '/' => 'sessions#new'

  # alternative signup paths to '/users/new'
  get '/signup' => 'users#new'
  get '/register' => 'users#new'

  # alternative login paths
  get '/signin' => 'sessions#new'
  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :listings
  resources :users
  resources :requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :requests
  has_one_attached :picture
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to '/login' unless current_user
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all

  end

  def myproperties

    @mylistings = Listing.where(user_id: session[:user_id])

  end

  def show
    @listing = Listing.find(params[:id])
    session[:listing_id] = @listing.id
    @bookings = Booking.where("listing_id = #{@listing.id}")

  end

  def new
    redirect_to '/login' if !session[:user_id]
    @listing = Listing.new
    @user_id = session[:user_id]
  end

  def create
    start_date = params[:listing][:from_date]
    end_date = params[:listing][:to_date]

    parsed_start = Date.parse(start_date)
    parsed_end = Date.parse(end_date)

    @user = User.find(session[:user_id])
    @listing = @user.listings.create(listing_params)  #creating a listing with the user (found with the session id) as a foreign key

      (parsed_start..parsed_end).each do |date|
      @booking = @listing.bookings.create(date: date, availability: true)


    end

    @listing.picture.attach(params[:listing][:picture])


    redirect_to listings_index_path
  end



  def edit

  end

  private

  def listing_params

    params.require(:listing).permit(:title, :address_first_line, :address_second_line, :address_post_code, :address_city, :address_country, :description, :price)

  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @requests = Request.where(user_id: session[:user_id])



  end

  def requestsreceived

    @listings = Listing.where("user_id = #{session[:user_id]}")

    @requests_received = []
    @listings.each do |listing|
    @requests_received << Request.where("listing_id = #{listing.id}")
    end

    @requests_received = @requests_received.flatten


  end

  # def show
  #   @request = Request.find(params[:id])
  #
  # end

  def new
    @listing = Listing.find(session[:listing_id])
    @bookings = Booking.where("listing_id = #{@listing.id}")
    @user = User.find(session[:user_id])
    @request = Request.new

  end

  def create
    booking_id = params[:availability]
    message = params[:message]

    booking = Booking.find(booking_id)




    @request = Request.create(user_id: session[:user_id],date: booking.date, message: message, listing_id: session[:listing_id])

    session[:listing_id] = nil

    redirect_to '/requests/index'


    # @request = Request.create(request_params)
  end

  def update

    @request = Request.find(params[:id])
    @request.update(status: 'approved')

    @bookings = Booking.where(["date = :date and listing_id = :listing_id", { date: @request.date, listing_id: @request.listing_id}])


    @bookings.each do |booking|
      p "individual"
      p booking
    Booking.delete(booking.id)
    end

    redirect_to '/requests/index'

    #  we need to delete the dates that have been requested (once approved) from the bookings table as those dates should no lonher exist once theyve been booked.



  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
       session[:user_id] = user.id
       flash[:success] = 'Successfully Logged In!'
       redirect_to listings_index_path
      else
       flash[:warning] = 'Invalid Username or Password'
       redirect_to '/login'
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Successfully Logged Out!'
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    # flashes a notification if invalid
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'Successfully created user!'
      redirect_to listings_index_path
    # else     will implement when 2 users use same email
    #   flash[:warning] = 'Invalid email or password'
    #   redirect_to '/user/new'
    end
  end

  def edit
  end

  def delete
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :email, :phone_number, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<div class="wrapper">
  <body>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="https://github.com/KajaMaria/Airbe_or_not_to_be">
            About
          </a>

          <%=link_to('Available properties', '/listings', method: :get, class: 'navbar-item')%>


          <% if current_user %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Hi <%= current_user.name%>! What would you like to do?
            </a>

            <div class="navbar-dropdown">
              <%=link_to('List my property', '/listings/new', method: :get, class: 'navbar-item')%>
              <%=link_to('View my properties', '/listings/myproperties', method: :get, class: 'navbar-item')%>
              <%=link_to('Requests I\'ve sent', '/requests/index', method: :get, class: 'navbar-item')%>
              <%=link_to('Requests I\'ve received', '/requests/requestsreceived', method: :get, class: 'navbar-item')%>

              <!-- <a class="navbar-item">
                Requests I've received
              </a> -->
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
          <% end %>
        </div>

        <% if current_user%>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <%=link_to('Log out', '/logout', class: 'button is-primary')%>
              </div>
            </div>
          </div>

        <% else %>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <%=link_to('Sign up', '/signup', class: 'button is-primary')%>
                <%=link_to('Log in', '/login', class: 'button is-primary')%>
              </div>
            </div>
          </div>
        <% end %>



      </div>
    </nav>

    <div class="clever-container">
      <%= yield %>
    </div>

  </body>

</div>

  <footer class="footer">
<div class="content has-text-centered">
  <p>
    <strong>Team Awesome</strong> by <a href="https://github.com/KajaMaria/Airbe_or_not_to_be">Welcome to this pretty page</a>.
    <a href="https://github.com/KajaMaria/Airbe_or_not_to_be">:)</a>. The website content
    is awesome <a href="https://github.com/KajaMaria/Airbe_or_not_to_be"></a>.
  </p>
</div>
</footer>

</html>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<h1 class="title is-1">Available Listings </h1>


  <div>
  <a >
    <%= button_to "New Listing", { action: "new" }, method: :get, class: "button is-link is-large is-fullwidth"%>
  </a>
  </div>


<div class="container is-centered listing-list columns is-multiline">
  <% @listings.each do |listing| %>
    <% if Booking.where(listing_id: listing.id).any? %>
      <div class="card column is-narrow listing">

        <div class="card-image">
            <figure class="image is-4by3">

              <% if listing.picture.attached? %>
                  <image src="<%=(url_for(listing.picture))%>">
              <% else %>
              <%= image_tag ('placeholder.jpg') %>
              <% end %>
            </figure>
        </div>

        <div class="card-content">
            <h2 class="title">
              <span class="listing-title"><%= link_to listing.title, listing_path(listing) %></span>
              <span class="listing-expand-button">[+]</span>
            </h2>
            <p hidden class="content listing-description"> <%= listing.description %> </p>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

<h1 class="title is-1"> Unavailable properties</h1>
<div class="container listing-list">

  <% @listings.each do |listing| %>
    <% if !Booking.where(listing_id: listing.id).any? %>
    <div class="card listing">

      <div class="card-content">
        <h2 class="title">
          <span class="listing-title"><%= link_to listing.title, listing_path(listing) %></span>
          <span class="listing-expand-button">[+]</span>
        </h2>
        <p hidden class="content listing-description"> <%= listing.description %> </p>
      </div>
    </div>
    <% end %>
  <% end %>

</div>

app/views/listings/myproperties.html.erb
<h1 class="title is-1">My properties</h1>


  <div>
  <a >
    <%= button_to "New Listing", { action: "new" }, method: :get, class: "button is-link is-large is-fullwidth"%>
  </a>
  </div>


<div class="container is-centered listing-list columns is-multiline">
  <% @mylistings.each do |listing| %>

      <div class="card column is-narrow listing">

        <div class="card-image">
            <figure class="image is-4by3">

              <% if listing.picture.attached? %>
                  <image src="<%=(url_for(listing.picture))%>">
              <% else %>
              <%= image_tag ('placeholder.jpg') %>
              <% end %>
            </figure>
        </div>

        <div class="card-content">
            <h2 class="title">
              <span class="listing-title"><%= link_to listing.title, listing_path(listing) %></span>
              <span class="listing-expand-button">[+]</span>
            </h2>
            <p hidden class="content listing-description"> <%= listing.description %> </p>
        </div>

      </div>
  <% end %>
</div>

app/views/listings/new.html.erb
<div class="container add-top-margin">


  <div class="columns is-centered">
    <div class="column add-padding is-narrow box has-background-white box-radius box-shadow">

      <p class="title is-1">List my property</p>

      <%= form_with model: @listing do |form| %>

      <label class="label">Title</label>
      <div class="field">
        <p class="control">
          <%= form.text_field :title, class:'input',placeholder: "title" %>
        </p>
      </div>

      <label class="label">Address</label>
      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field"
            <p class="control">
              <%= form.text_field :address_first_line, class:'input', placeholder: "address(first line)" %>
            </p>
          </div>
          <div class="field">
            <p class="control">
              <%= form.text_field :address_second_line,class:'input', placeholder: "address(second line)" %>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field">
            <p class="control">
              <%= form.text_field :address_post_code, class:'input',placeholder: "post code" %>
            </p>
          </div>

          <div class="field">
            <p class="control">
                <%= form.text_field :address_city, class:'input',placeholder: "city" %>
            </p>
          </div>

          <div class="field">
            <p class="control">
              <%= form.text_field :address_country,class:'input', placeholder: "country" %>
            </p>
          </div>
        </div>
      </div>


      <label class="label">Description</label>
      <div class="field">
        <p class="control">
          <%= form.text_area :description,class:'textarea', placeholder: "description" %>
        </p>
      </div>

      <label class="label">Price per night</label>
      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field is-expanded">
            <div class="field has-addons">
              <p class="control">
                <a class="button is-static">
                  £
                </a>
              </p>
              <p class="control is-expanded">
                <%= form.number_field :price, class:'input',placeholder: "price" %>
              </p>
            </div>
          </div>
        </div>
      </div>

      <label class="label">Available dates</label>
      <div class="field is-horizontal">
        <div class="field-body">

          <div class="field">
            <p class="control">
              <%= form.date_field :from_date, class: 'input', id:'datepicker' %>
            </p>
          </div>

          <div class="field">
            <p class="control">
              <%= form.date_field :to_date, class: 'input', id:'datepicker' %>
            </p>
          </div>
        </div>
      </div>


      <%= form.label "Picture", class: "label" %>
      <div class="field">
        <%= form.file_field :picture, class: "control" %>
      </div>

      <div class="field">
          <p class="control">
            <%= form.submit 'Create', class:'button is-success' %>
          </p>
      </div>



        <%end%>

    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="card">
  <div class="card-image">
    <figure class="image is-4by3">

      <% if @listing.picture.attached? %>
          <image src="<%=(url_for(@listing.picture))%>">
      <% else %>
      <%= image_tag 'placeholder.jpg' %>
      <% end %>
      <!-- <img src="https://pixabay.com/get/57e8dd454c50ac14f6da8c7dda6d49214b6ac3e45657754e712c7bd296/log-cabin-1886620_1280.jpg" alt="Placeholder image"> -->
    </figure>
  </div>
<div class="card-content">
<div class="media">
  <!-- <div class="media-left">
    <figure class="image is-24x24">

    </figure>
  </div> -->



  <div class="field media content">
    <!-- <p class="control title is-3"> <%= @listing.title %> </p> -->
      <p class="subtitle pacifico is-1">"<%= @listing.description %>"</p>
  </div>
</div>

<div class="columns is-2">

<div class="column our-little-box box box-radius box-background-color box-padding box-shadow">
  <p class="control subtitle is-3"> <%= @listing.title %></p>
  <div class="is-size-4">
    <p> <%= @listing.address_first_line %> </p>

    <p><%= @listing.address_second_line %></p>
    <p><%= @listing.address_post_code %></p>
    <p><%= @listing.address_city %></p>
    <p><%= @listing.address_country %></p>
  </div>
</div>



<% if Booking.where(listing_id: @listing.id).any? %>

<div class="column our-little-box box box-radius box-background-color box-padding box-shadow">
    <p class="is-size-4">£<%= @listing.price %> per night</p>
</div>

<div class="column our-little-box  box box-radius box-background-color box-padding box-shadow">
    <div class="field">
      <label class="label is-4">Availability:</label>
      <div class="control">
        <div class="select">
          <%= select_tag "availability", options_from_collection_for_select(@bookings,"id", "date")%>
        </div>
      </div>
    </div>


</div>
<!-- end of columns-->
  </div>

    <div class="content">
      <br>
     <a href="#">#facebook</a> <a href="#">#twitter</a>
   </div>
 </div>
</div>

<div>
<a >
  <%= button_to "Make a request", '/requests/new', method: :get, class: "button is-danger is-large is-fullwidth"%>
</a>
</div>

<% else %>
<%= "Sorry, this property is unavailable" %>
<% end %>
</div>
</div>

<div>

app/views/requests/index.html.erb
<div class="container add-top-margin">

  <h1 class="title is-3">Requests you've made</h1>

  <div class="columns add-top-margin is-multiline is-centered">


    <% @requests.each do |request| %>
    <div class="column box is-narrow">
    <p class="title is-2"><%= Listing.find(request.listing_id).title %></p>
    <p><%= Listing.find(request.listing_id).description %></p>
    <p><%= request.message %></p>
    <p>Status:<%= request.status %></p>
    </div>
    <% end %>

  </div>


</div>

app/views/requests/new.html.erb
<div class="columns is-centered add-top-margin">
  <div class="column is-narrow box">
<%= @listing.title  %>
<%= @listing.description  %>


    <%= form_tag("/requests", method: "post") do %>
      <div class="field">
        <label class="label">Please choose date!</label>
        <div class="control">
          <div class="select">
            <%= select_tag "availability", options_from_collection_for_select(@bookings,"id", "date")%>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label">Please enter a message to your host:</label>
        <div class="control">
          <%= text_area :message, nil, class: 'textarea' %>
        </div>
      </div>

      <%= submit_tag "Send request",class: "button is-success" %>
    <% end %>
  </div>
</div>

app/views/requests/requestsmade.html.erb
<h1>Requests you've received</h1><br>

<% @requests_received.each do |request| %>
<%= Listing.find(request.listing_id).title %>
<%= Listing.find(request.listing_id).description %>
<%= request.message %>
<%= request.status %>

  <% if request.status == "pending" %>
    <%= button_to "Confirm", "/requests/#{request.id}", method: :patch, class: "confirm-button" %>
  <% end %>
<% end %>

app/views/requests/requestsreceived.html.erb
<div class="container add-top-margin">

  <div>
    <h1 class="title is-3">Requests you've received</h1>
  </div>

  <div class="columns add-top-margin is-multiline is-centered">



      <% @requests_received.each do |request| %>
      <div class="column box is-narrow">
      <p class="title is-2"><%= Listing.find(request.listing_id).title %></p>
      <p><%= Listing.find(request.listing_id).description %></p>
      <p><%= request.message %></p>
      <p>Status: <%= request.status %></p>

        <% if request.status == "pending" %>
          <%= button_to "Confirm", "/requests/#{request.id}", method: :patch, class: "confirm-button button is-success" %>
        <% end %>


      </div>
      <% end %>


  </div>
</div>

app/views/requests/show.html.erb
<h1>Requests#show</h1>
<p>Find me in app/views/requests/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1> Welcome <%= @users.name %></h1>
<ul>
  <% @users.each do |user| %>
    <li> <%= link_to user.username, users_index_url(user) %> </li>
  <% end %>
</ul>

<%= button_to "See your requests", '/requests/index', method: :get %> 

app/views/users/new.html.erb
<div class="container add-top-margin">
  <div class="columns is-centered">
    <div class="column add-padding is-narrow box has-background-white box-radius box-shadow">

      <p class="title is-3"><%= flash[:warning] %></p>
      <p class="title is-1">Sign up</p>

      <%= form_with model: @user do |form| %>
        <div class="field">
          <label class="label">Username</label>
          <div class="control">
            <%= form.text_field :username, class: 'input', placeholder: "username" %>
          </div>
        </div>
        <div class="field">
          <label class="label">Name</label>
          <div class="control">
            <%= form.text_field :name, class: 'input', placeholder: "name" %>
          </div>
        </div>
        <div class="field">
          <label class="label">Email</label>
          <div class="control has-icons-left has-icons-right">
            <%= form.email_field :email, class: 'input', placeholder: "email" %>
              <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
              </span>
          </div>
        </div>

        <div class="field">
          <label class="label">Phone Number</label>
          <div class="field-body">
            <div class="field is-expanded">
              <div class="field has-addons">
                <p class="control">
                  <a class="button is-static">
                    +44
                  </a>
                </p>
                <p class="control is-expanded">
                  <%= form.telephone_field :phone_number, class:'input', placeholder: "number" %>
                </p>
              </div>
            </div>
          </div>
        </div>

        <div class="field">
          <label class="label">Password</label>
          <p class="control has-icons-left">
            <%= form.password_field :password, class: 'input', placeholder: "password" %>
          <span class="icon is-small is-left">
            <i class="fas fa-lock"></i>
          </span>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= form.submit 'Sign up', class:'button is-success' %>
          </p>
        </div>


      <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>